name: 3. Enviar Novo Chamado

on:
  repository_dispatch:
    types: [send_chamado_notification]

jobs:
  send_message:
    runs-on: ubuntu-22.04
    
    steps:
      - name: 1. Checkout do Repositório
        uses: actions/checkout@v4

      - name: 2. Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 3. Instalar Dependências Básicas
        run: |
          npm init -y
          npm install mongoose @supabase/supabase-js dotenv @whiskeysockets/baileys pino jimp@0.16.13 --legacy-peer-deps

      - name: 4. Rodar Script de Envio de Mensagem
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          PAYLOAD: ${{ toJson(github.event.client_payload) }}
        run: node whatsapp_sender_func.js
